repos:
  - repo: https://github.com/python/back.git
    rev: 23.9.1
    hooks:
      - id: black
        args: [--line-length", "120"]
        language_version: python3
  - repo: https://github.com/pycqa/flake8.git
    rev: 6.1.0
    hooks:
      - id: flake8
        args: 
          [
            "--max-line-length",
            "120",
            "--extend-ignore",
            "E203,BLK100,W605,ANN002,ANN003,ANN101,ANN204",
          ]
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: 
            [
              "--profile", 
              "black",
              "--line-length", 
              "120",
              "--extend-skip",
              "__init__.py",
              "--filter-files",
            ]
